services:
  rahoot:
    build:
      context: .
      dockerfile: Dockerfile
    image: kriziw/rahoot:latest
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./media:/app/media
