/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as authLayoutRouteImport } from './pages/(auth)/layout'
import { Route as authIndexRouteImport } from './pages/(auth)/index'
import { Route as PartyGameIdRouteImport } from './pages/party/$gameId'
import { Route as authManagerIndexRouteImport } from './pages/(auth)/manager/index'
import { Route as PartyManagerGameIdRouteImport } from './pages/party/manager/$gameId'

const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLayoutRoute,
} as any)
const PartyGameIdRoute = PartyGameIdRouteImport.update({
  id: '/party/$gameId',
  path: '/party/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const authManagerIndexRoute = authManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => authLayoutRoute,
} as any)
const PartyManagerGameIdRoute = PartyManagerGameIdRouteImport.update({
  id: '/party/manager/$gameId',
  path: '/party/manager/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/party/$gameId': typeof PartyGameIdRoute
  '/': typeof authIndexRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/manager/': typeof authManagerIndexRoute
}
export interface FileRoutesByTo {
  '/party/$gameId': typeof PartyGameIdRoute
  '/': typeof authIndexRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/manager': typeof authManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/party/$gameId': typeof PartyGameIdRoute
  '/(auth)/': typeof authIndexRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/(auth)/manager/': typeof authManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/party/$gameId' | '/' | '/party/manager/$gameId' | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to: '/party/$gameId' | '/' | '/party/manager/$gameId' | '/manager'
  id:
    | '__root__'
    | '/(auth)'
    | '/party/$gameId'
    | '/(auth)/'
    | '/party/manager/$gameId'
    | '/(auth)/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  PartyGameIdRoute: typeof PartyGameIdRoute
  PartyManagerGameIdRoute: typeof PartyManagerGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/party/$gameId': {
      id: '/party/$gameId'
      path: '/party/$gameId'
      fullPath: '/party/$gameId'
      preLoaderRoute: typeof PartyGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/manager/': {
      id: '/(auth)/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof authManagerIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/party/manager/$gameId': {
      id: '/party/manager/$gameId'
      path: '/party/manager/$gameId'
      fullPath: '/party/manager/$gameId'
      preLoaderRoute: typeof PartyManagerGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authLayoutRouteChildren {
  authIndexRoute: typeof authIndexRoute
  authManagerIndexRoute: typeof authManagerIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authIndexRoute: authIndexRoute,
  authManagerIndexRoute: authManagerIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  PartyGameIdRoute: PartyGameIdRoute,
  PartyManagerGameIdRoute: PartyManagerGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
