/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as authLayoutRouteImport } from './pages/(auth)/layout'
import { Route as authIndexRouteImport } from './pages/(auth)/index'
import { Route as PartyGameIdRouteImport } from './pages/party/$gameId'
import { Route as ManagerConfigRouteImport } from './pages/manager/config'
import { Route as ManagerQuizzLayoutRouteImport } from './pages/manager/quizz/layout'
import { Route as ManagerQuizzIndexRouteImport } from './pages/manager/quizz/index'
import { Route as authManagerIndexRouteImport } from './pages/(auth)/manager/index'
import { Route as PartyManagerGameIdRouteImport } from './pages/party/manager/$gameId'
import { Route as ManagerQuizzQuizzIdRouteImport } from './pages/manager/quizz/$quizzId'

const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLayoutRoute,
} as any)
const PartyGameIdRoute = PartyGameIdRouteImport.update({
  id: '/party/$gameId',
  path: '/party/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerConfigRoute = ManagerConfigRouteImport.update({
  id: '/manager/config',
  path: '/manager/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerQuizzLayoutRoute = ManagerQuizzLayoutRouteImport.update({
  id: '/manager/quizz',
  path: '/manager/quizz',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerQuizzIndexRoute = ManagerQuizzIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerQuizzLayoutRoute,
} as any)
const authManagerIndexRoute = authManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => authLayoutRoute,
} as any)
const PartyManagerGameIdRoute = PartyManagerGameIdRouteImport.update({
  id: '/party/manager/$gameId',
  path: '/party/manager/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerQuizzQuizzIdRoute = ManagerQuizzQuizzIdRouteImport.update({
  id: '/$quizzId',
  path: '/$quizzId',
  getParentRoute: () => ManagerQuizzLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/manager/quizz': typeof ManagerQuizzLayoutRouteWithChildren
  '/manager/config': typeof ManagerConfigRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/': typeof authIndexRoute
  '/manager/quizz/$quizzId': typeof ManagerQuizzQuizzIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/manager/': typeof authManagerIndexRoute
  '/manager/quizz/': typeof ManagerQuizzIndexRoute
}
export interface FileRoutesByTo {
  '/manager/config': typeof ManagerConfigRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/': typeof authIndexRoute
  '/manager/quizz/$quizzId': typeof ManagerQuizzQuizzIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/manager': typeof authManagerIndexRoute
  '/manager/quizz': typeof ManagerQuizzIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/manager/quizz': typeof ManagerQuizzLayoutRouteWithChildren
  '/manager/config': typeof ManagerConfigRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/(auth)/': typeof authIndexRoute
  '/manager/quizz/$quizzId': typeof ManagerQuizzQuizzIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/(auth)/manager/': typeof authManagerIndexRoute
  '/manager/quizz/': typeof ManagerQuizzIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/manager/quizz'
    | '/manager/config'
    | '/party/$gameId'
    | '/'
    | '/manager/quizz/$quizzId'
    | '/party/manager/$gameId'
    | '/manager/'
    | '/manager/quizz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/manager/config'
    | '/party/$gameId'
    | '/'
    | '/manager/quizz/$quizzId'
    | '/party/manager/$gameId'
    | '/manager'
    | '/manager/quizz'
  id:
    | '__root__'
    | '/(auth)'
    | '/manager/quizz'
    | '/manager/config'
    | '/party/$gameId'
    | '/(auth)/'
    | '/manager/quizz/$quizzId'
    | '/party/manager/$gameId'
    | '/(auth)/manager/'
    | '/manager/quizz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  ManagerQuizzLayoutRoute: typeof ManagerQuizzLayoutRouteWithChildren
  ManagerConfigRoute: typeof ManagerConfigRoute
  PartyGameIdRoute: typeof PartyGameIdRoute
  PartyManagerGameIdRoute: typeof PartyManagerGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/party/$gameId': {
      id: '/party/$gameId'
      path: '/party/$gameId'
      fullPath: '/party/$gameId'
      preLoaderRoute: typeof PartyGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/config': {
      id: '/manager/config'
      path: '/manager/config'
      fullPath: '/manager/config'
      preLoaderRoute: typeof ManagerConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/quizz': {
      id: '/manager/quizz'
      path: '/manager/quizz'
      fullPath: '/manager/quizz'
      preLoaderRoute: typeof ManagerQuizzLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/quizz/': {
      id: '/manager/quizz/'
      path: '/'
      fullPath: '/manager/quizz/'
      preLoaderRoute: typeof ManagerQuizzIndexRouteImport
      parentRoute: typeof ManagerQuizzLayoutRoute
    }
    '/(auth)/manager/': {
      id: '/(auth)/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof authManagerIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/party/manager/$gameId': {
      id: '/party/manager/$gameId'
      path: '/party/manager/$gameId'
      fullPath: '/party/manager/$gameId'
      preLoaderRoute: typeof PartyManagerGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/quizz/$quizzId': {
      id: '/manager/quizz/$quizzId'
      path: '/$quizzId'
      fullPath: '/manager/quizz/$quizzId'
      preLoaderRoute: typeof ManagerQuizzQuizzIdRouteImport
      parentRoute: typeof ManagerQuizzLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authIndexRoute: typeof authIndexRoute
  authManagerIndexRoute: typeof authManagerIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authIndexRoute: authIndexRoute,
  authManagerIndexRoute: authManagerIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface ManagerQuizzLayoutRouteChildren {
  ManagerQuizzQuizzIdRoute: typeof ManagerQuizzQuizzIdRoute
  ManagerQuizzIndexRoute: typeof ManagerQuizzIndexRoute
}

const ManagerQuizzLayoutRouteChildren: ManagerQuizzLayoutRouteChildren = {
  ManagerQuizzQuizzIdRoute: ManagerQuizzQuizzIdRoute,
  ManagerQuizzIndexRoute: ManagerQuizzIndexRoute,
}

const ManagerQuizzLayoutRouteWithChildren =
  ManagerQuizzLayoutRoute._addFileChildren(ManagerQuizzLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  ManagerQuizzLayoutRoute: ManagerQuizzLayoutRouteWithChildren,
  ManagerConfigRoute: ManagerConfigRoute,
  PartyGameIdRoute: PartyGameIdRoute,
  PartyManagerGameIdRoute: PartyManagerGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
